<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="hp" ignored="4" name="Test1" tests="2" failures="1" timestamp="07 Apr 2020 16:33:10 GMT" time="41.457" errors="0">
  <testcase name="run2" time="0.016" classname="Base.testcase2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Base.testcase2.run2(testcase2.java:15)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- run2 -->
  <testcase name="run" time="14.945" classname="Base.Testcase"/>
  <testcase name="@BeforeTest setUP" time="0.0" classname="Base.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeTest setUP -->
  <testcase name="@AfterSuite flush" time="0.0" classname="Base.BaseClass">
    <ignored/>
  </testcase> <!-- @AfterSuite flush -->
  <testcase name="@AfterTest endapp" time="0.0" classname="Base.BaseClass">
    <ignored/>
  </testcase> <!-- @AfterTest endapp -->
  <testcase name="@BeforeSuite extentStart" time="0.0" classname="Base.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite extentStart -->
</testsuite> <!-- Test1 -->
